# 색상 출력

OpenCV를 활용한 주요 색상 추출. K-means clustering 활용

In [1]:
import os

home_path = os.path.expanduser('~')

print (home_path)

C:\Users\emily


In [2]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [7]:
import cv2, numpy as np
from sklearn.cluster import KMeans

def visualize_colors(cluster, centroids):
    # Get the number of different clusters, create histogram, and normalize
    labels = np.arange(0, len(np.unique(cluster.labels_)) + 1)
    (hist, _) = np.histogram(cluster.labels_, bins = labels)
    hist = hist.astype("float")
    hist /= hist.sum()

    # Create frequency rect and iterate through each cluster's color and percentage
    rect = np.zeros((50, 300, 3), dtype=np.uint8)
    colors = sorted([(percent, color) for (percent, color) in zip(hist, centroids)])
    start = 0
    for (percent, color) in colors:
        print(color, "{:0.2f}%".format(percent * 100))
        end = start + (percent * 300)
        cv2.rectangle(rect, (int(start), 0), (int(end), 50), \
                      color.astype("uint8").tolist(), -1)
        start = end
    return rect

# Load image and convert to a list of pixels
image = cv2.imread('C:/Users/emily/desktop/13.png')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
reshape = image.reshape((image.shape[0] * image.shape[1], 3))

# Find and display most dominant colors
cluster = KMeans(n_clusters=10).fit(reshape)
visualize = visualize_colors(cluster, cluster.cluster_centers_)
visualize = cv2.cvtColor(visualize, cv2.COLOR_RGB2BGR)
cv2.imshow('visualize', visualize)
cv2.waitKey()

[115.44637681 160.56908213 211.54492754] 0.32%
[205.446875   205.33697917 205.31875   ] 0.58%
[218.22813345 220.34806132 222.62714157] 0.70%
[189.21804753 188.11592807 188.89434811] 0.96%
[175.59146579 205.15141587 238.68000624] 4.05%
[150.94167378 186.47549058 225.21686186] 7.97%
[168.75340508 199.95149765 236.0835302 ] 10.73%
[162.76768582 195.30988403 232.92253558] 11.50%
[157.11162881 190.92423717 228.7403346 ] 14.26%
[230.97661306 230.97438423 230.97028015] 48.94%


-1